name: Build and Run Shiny App

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"

env:
  RENV_PATHS_ROOT: ~/.cache/R/renv

jobs:
  run-shiny-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.3  # Vous pouvez ajuster cette version selon vos besoins
          use-public-rspm: true

      - name: Cache Renv packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install and activate renv
        env:
          RENV_PATHS_ROOT: ${{ env.RENV_PATHS_ROOT }}
        run: |
          R -e "install.packages('renv', repos='https://cran.r-project.org/')"
          R -e "renv::activate()"
          R -e "renv::restore()"

      - name: Run Shiny App
        run: |
          R -e "shiny::runApp('.', port=3838, host='0.0.0.0')"
