name: Build and Push Docker Image

on: 
  push:
    branches:
      - 'main'

env:
  CACHE_IMAGE: ghcr.io/bastienird/minorshinyappTest-cache
  DOCKER_BUILDKIT: 1
  RENV_PATHS_ROOT: ~/.cache/R/renv

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/bastienird/minorshinyappTest
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.url=${{ github.repository }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.title=minorshinyappTest
            org.opencontainers.image.description=Minor shiny app to test renv cache
            org.opencontainers.image.vendor=IRD
            org.opencontainers.image.author=Bastien Grasset <bastien.grasset@ird.fr>

      - name: Get R and OS version
        id: get-version
        run: |
          echo "os-version=$(lsb_release -d | cut -f2)" >> $GITHUB_ENV
          echo "r-version=$(R --version | head -n 1)" >> $GITHUB_ENV

      - name: Restore Renv package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install and activate renv #these is to test if all packages are up to date and can be installed
        run: |
          Rscript -e "install.packages('renv', repos='https://cran.r-project.org')"
          Rscript -e "renv::restore()"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Create and bootstrap builder
        run: |
          docker buildx create --use --name builder
          docker buildx inspect builder --bootstrap

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --cache-from type=registry,ref=$CACHE_IMAGE:latest \
            --cache-to type=registry,ref=$CACHE_IMAGE:latest,mode=max \
            --tag ghcr.io/bastienird/minorshinyappTest:latest \
            --build-arg RENV_PATHS_ROOT=${{ env.RENV_PATHS_ROOT }} \
            --push .
